[build]
builder = "dockerfile"
dockerfilePath = "./src/HousesPapon.API/Dockerfile"

[deploy]
restartPolicyType = "always"
healthcheckPath = "/swagger/index.html"

[env]
ASPNETCORE_ENVIRONMENT = "Production"