[build]
builder = "dockerfile"
dockerfilePath = "./src/HousesPapon.API/Dockerfile"

[deploy]
startCommand = "dotnet HousesPapon.API.dll"
restartPolicyType = "always"
healthcheckPath = "/swagger/index.html"